/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mini_knight.glb --transform 
Files: mini_knight.glb [653.02KB] > C:\Users\amale\OneDrive\Desktop\PortFolio\public\models\mini_knight-transformed.glb [195.36KB] (70%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Mini_Knight(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/mini_knight-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="FAB_converted">
        <group name="Object_5" scale={0.01}>
          <primitive object={nodes.mixamorigHips_01} />
        </group>
        <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_48.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_49.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_50.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_52.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_53.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_54.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_56.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_57.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_58.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_60.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_61.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_63.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_65.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_66.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_67.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_69.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_71.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_72.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_73.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_75.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_76.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
        <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_77.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mini_knight-transformed.glb')
